spring:
  application:
    name: backend
  datasource:
    url: jdbc:sqlite:../database/dev.db
    driver-class-name: org.sqlite.JDBC
  security:    
    jwt:
      secret: "this_is_a_very_long_yet_insecure_jwt_secret_123!"
      expiration: 3600000