name: Tag Blog File

permissions:
  contents: write

on:
  push:
    paths:
      - 'blog/**'

jobs:
  tag-on-new-blog-file:
    runs-on: ubuntu-latest
    if: github.event.commits != null
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed blog files (added or modified)
        id: changedfiles
        run: |
          git fetch origin ${{ github.event.before }}
          git diff --name-status ${{ github.event.before }} ${{ github.sha }} | awk '/^[AM]\tblog\// {print $2}' > changedfiles.txt
          cat changedfiles.txt

      - name: Tag for each changed file (force update)
        run: |
          while read file; do
            [ -z "$file" ] && continue
            filename=$(basename "$file")
            tagname="${filename%.*}"
            git tag -f "$tagname"
            git push -f origin "$tagname"
          done < changedfiles.txt
