name: Update Blog

permissions:
  contents: write

on:
  push:
    paths:
      - blog/**
    branches:
      - main
  workflow_dispatch:

jobs:
  publish-blog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 

      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache 
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material 
      - run: mkdocs gh-deploy --force

  tag-on-new-blog-file:
    runs-on: ubuntu-latest
    if: github.event.commits != null
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed blog files (added or modified)
        id: changedfiles
        run: |
          git fetch origin ${{ github.event.before }}
          git diff --name-status ${{ github.event.before }} ${{ github.sha }} | awk '/^[AM]\tblog\// {print $2}' > changedfiles.txt
          cat changedfiles.txt

      - name: Tag for each changed file (force update)
        run: |
          while read file; do
            [ -z "$file" ] && continue
            filename=$(basename "$file")
            tagname="${filename%.*}"
            git tag -f "$tagname"
            git push -f origin "$tagname"
          done < changedfiles.txt
